### ISSUE TITLE
Black screen after installing 21.10.8

### ISSUE THREAD

**Issue by tomaswarynyca** [flathub/io.exodus.Exodus#108]
Hello, this error appeared after updating
I am on ElementaryOS 6

![image](https://user-images.githubusercontent.com/41587659/137137372-6529f960-0dda-4abd-bb0e-3fc20b3d1b4d.png)

**Comment by tomaswarynyca** [comment]
Ohh it works! :rocket:
Would it be good to upgrade to v21.10.11?

**Comment by AHappyUser** [comment]
Here is [Version 21.10.11](https://github.com/flathub/io.exodus.Exodus/pull/109)
The app seems to work fine for me now.
