### ISSUE TITLE
Exodus is not up to date

### ISSUE THREAD

**Issue by VosaXalo** [flathub/io.exodus.Exodus#13]
On the site of Exodus https://www.exodus.io/releases/ is available the latest version 19.4.12.
The flatpak package is still at the version 19.2.5 .

Thanks.

**Comment by sysfu** [comment]
This should be pretty easy for a non-coder to submit a pull request for. [If you look at the last commit](https://github.com/flathub/io.exodus.Exodus/commit/cf0dceb11752430552abaecdf75f9570d07b2ab4) for the version update it's just updating two files with the new download links and file sizes.

**Comment by TingPing** [comment]
Fixed by d32c1eac568ceb324037df38b8442475cf8a58cb
