### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/io.exodus.Exodus#38]

**Comment by AHappyUser** [comment]
Should both the `runtime-version` and `base-version` be updated?

`  "base": "org.electronjs.Electron2.BaseApp",`
`  "base-version": "18.08",`
`  "runtime": "org.freedesktop.Platform",`
`  "runtime-version": "18.08",`

**Comment by LeandroStanger** [comment]
Yes

**Comment by AHappyUser** [comment]
The runtime is now at version 19.08.
