### ISSUE TITLE
error: Nothing matches io.exodus.Exodus in remote flathub

### ISSUE THREAD

**Issue by timh2020** [flathub/io.exodus.Exodus#76]
I'm just trying to install exodus:
flatpak install flathub io.exodus.Exodus

but getting this error:
error: Nothing matches io.exodus.Exodus in remote flathub

Any ideas? Thanks.

**Comment by AHappyUser** [comment]
@timh2020  Try reinstalling flatpak repo.
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

Then reboot

You can list the installed flatpak repositories with.
`flatpak remotes`

And search all installed repositories for Exodus with.
`flatpak remote-ls flathub | grep Exodus`

![Screenshot from 2021-01-11 10-13-03](https://user-images.githubusercontent.com/50184095/104199957-14be2d00-53f6-11eb-814a-afbc9cdd75d1.png)

**Comment by timh2020** [comment]
Thanks, I did try the reinstall & reboot, but still no joy...
I installed cherrytree y'day no probs, and it shows up, but that's all.
Screenshot (hopefully):
![Screenshot from 2021-01-11 16-30-44](https://user-images.githubusercontent.com/64158356/104210847-41406c00-542b-11eb-8a19-15b3f9c4f842.png)

**Comment by timh2020** [comment]
BTW, I've had a look at the remote-ls list, and it's quite long & not empty...
I can find GIMP, & BitTorrent (eg)
But not Zoom, Spotify, Firefox, Exodus...
Is it getting the data direct or is there a local cache that might need deleting, or something?

**Comment by AHappyUser** [comment]
Exodus is x86_64 only.  If you are on ARM it may not be available to install.
